### PR TITLE
Add support fonction to create pv and pvc

### PR DESCRIPTION
**Pull request by nitang22**

### CODE REVIEW

**Comment by fcarregen** [comment]
PV and PVC are normally resources created by helm charts
What is/are pain point(s) to have them as templates in generic_application chart?

**Comment by nitang22** [comment]
Same as we can create secrets, cm with support script k8s.sh. Why are we mentioning `generic_application` chart?

**Comment by fcarregen** [comment]
Don't approve, we're going to bypass helm chart usage and best practices
Need real world example...
The example with Nexus: it's just adding yaml files to create the PV/PVC so those functions aren't needed
Con of those functions: YAML aren't tracked by Argo CD with the state of the app

**Comment by nitang22** [comment]
This PR is **not** to bypass helm for solochain but to add generic functions to add pv and pvc inside kube like we do for the secrets, configmap, namespace etc... 
image

Plus Argo does not track at all, everything we have inside kubernetes

**Review by fcarregen — APPROVED** [review]

**Pull request merged**
